app = 'qwen3-vl-embedding'
primary_region = 'ord'

[build]
  image = 'registry.fly.io/qwen3-vl-embedding:latest'

[env]
  COG_LOG_LEVEL = 'debug'
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "60s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health-check"

[[vm]]
  size = 'performance-2x'
  memory = '48gb'
  gpu_kind = 'a100-pcie-40gb'